import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Salt-demo</title>
        <meta name="description" content="Generated by create next app" />
        
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        <span>
        <Link href="/register">Register</Link>
        <div></div>
        <Link href="/login">Login</Link>
        </span>
        </h1>
      </main>

    </div>
  )
}

export default Home
